// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0ZiLeYBTM5MDKUSxKHaJ0VL0wQjtxUw',
    appId: '1:195091042581:web:961524ecd0a3b0a64cd91c',
    messagingSenderId: '195091042581',
    projectId: 'atharapp-5a3a3',
    authDomain: 'atharapp-5a3a3.firebaseapp.com',
    storageBucket: 'atharapp-5a3a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsIehjKSYHTfwsY2ws48b8obAdRr2Mdec',
    appId: '1:195091042581:android:1fb5a36aaf6880ad4cd91c',
    messagingSenderId: '195091042581',
    projectId: 'atharapp-5a3a3',
    storageBucket: 'atharapp-5a3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6bKFdctPc_oGTDyfqILg7tnzcWXpj5FQ',
    appId: '1:195091042581:ios:d56dc51e161cebf64cd91c',
    messagingSenderId: '195091042581',
    projectId: 'atharapp-5a3a3',
    storageBucket: 'atharapp-5a3a3.appspot.com',
    iosBundleId: 'com.example.atharApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6bKFdctPc_oGTDyfqILg7tnzcWXpj5FQ',
    appId: '1:195091042581:ios:1978f760f687a3f14cd91c',
    messagingSenderId: '195091042581',
    projectId: 'atharapp-5a3a3',
    storageBucket: 'atharapp-5a3a3.appspot.com',
    iosBundleId: 'com.example.atharApp.RunnerTests',
  );
}
